### ISSUE TITLE
Is GetItemQuality using the correct name?

### ISSUE THREAD

**Issue by DosMike** [FlaminSarge/tf2idb#29]
browsing the source i noticed that `Native_GetItemQuality` is using `TF2IDB_GetItemSlotName` [here](https://github.com/FlaminSarge/tf2idb/blob/c2bc42e34c2a2e9a4e9ad0d0fe8cda564e970bb6/scripting/tf2idb.sp#L381), shouldn't that be `TF2IDB_GetItemQualityName`?

**Comment by FlaminSarge** [comment]
That's probably true.

Ideally everyone moves over to https://github.com/nosoop/SM-TFEconData and stops using this but I know that's not necessarily viable for some projects.

**Comment by nosoop** [comment]
As of last week, the [Econ Data compatibility shim](https://github.com/nosoop/SM-TFEconDataCompat) has rolling release builds; users are invited to test it out and contribute with bug reports / pull requests / coffee.

I'm not really sure what state it's in now since I don't have a need for it myself, but it passed my original litmus test of getting Bot Weapon Randomizer to run (after applying patches to the plugin to prevent runtime attribute copies).
